### PR TITLE
Removed extra "the" of background job model empty state(#246)

### LINKED ISSUE #246: Remove Redundant `the` from Background Jobs Model Empty State
## Current behavior
In the background jobs model empty state, there is a redundant occurrence of the word "the." This redundancy affects the clarity and professionalism of the user interface.

## Expected behavior
The redundant "the" should be removed from the background jobs model empty state to improve the overall consistency and readability of the interface.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
Screenshot 2023-10-11 at 2 35 21 PM

### PR DESCRIPTION
**Pull request by Jitisha-khede**
### Related Issues

Closes #246 

### Short Description and Why It's Useful

it is removing the extra the which is there in background job model empty state.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution.

We need to remove this line from [here](https://github.com/hotwax/preorder/blob/main/src/views/background-job-modal.vue#L17C43-L17C43) as well, and also need to update the key in the en.json file.

**Review by ymaheshwari1 — APPROVED** [review]

**Comment by ymaheshwari1** [comment]
@Jitisha-khede Please update the title of the PR, it should explain about the changes you have done in this PR.

**Comment by Jitisha-khede** [comment]
Done, have a look please

**Comment by Jitisha-khede** [comment]
Please merge this pull request under the label of hacktoberfest
.

**Pull request merged**
