### PR TITLE
Improved: Added support to refresh the related jobs. Also added checks to not allow any actions on the outdated job. (#288)

### PR DESCRIPTION
**Pull request by ravilodhi**
### Related Issues
#288 
#

### Short Description and Why It's Useful
Improved: Added support to refresh the related jobs. Also added checks to not allow any actions on the outdated job. (#288)

### Screenshots of Visual Changes before/after (If There Are Any)
Before
PO_RELATED_JOBS

After
PO_RELATED_JOBS_REFRESH

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/preorder#contribution-guideline)

### CODE REVIEW

**Comment by dt2patel** [comment]
@ravilodhi isn't there a way that we can just have the data update when job run time changes? There has to be a better solution here then asking user to refresh the page.

**Comment by ravilodhi** [comment]
@dt2patel The current solution was to at least ensure the existing functionality works correctly, rather than throwing an error when the current job is executed and a new record is created for the next execution.

We can definitely implement a solution like Firebase Cloud Messaging with web push notifications to receive job updates.

**Comment by dt2patel** [comment]
Why not just refresh automatically if we get error? We can auto fetch latest job and retry the same action that user attempted right?

**Comment by ravilodhi** [comment]
Yes, we can. The current Refresh Button pattern is inspired by the Job Manager app, where jobs are not refreshed automatically but instead require the user to manually initiate a refresh.

I will raise the PR to refresh the job automatically.

**Pull request merged**
